# Generated by Django 3.2.16 on 2023-04-03 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.DecimalField(decimal_places=0, max_digits=13)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'OFFER',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('minOffer', models.DecimalField(decimal_places=0, max_digits=13)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('reportable', models.BooleanField(default=True)),
                ('priority', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.category')),
            ],
            options={
                'db_table': 'PUBLICATION',
            },
        ),
        migrations.CreateModel(
            name='PublicationSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_column='sopType', max_length=45)),
                ('data', models.FileField(db_column='sopData', upload_to='publications_support_data')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='publications.publication')),
            ],
            options={
                'db_table': 'PUBLICATIONSUPPORT',
            },
        ),
    ]
