# Generated by Django 3.2.16 on 2023-03-26 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(db_column='comId', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(db_column='comText', max_length=256)),
                ('title', models.CharField(db_column='comTitle', max_length=45, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='comCreatedAt')),
                ('parent', models.ForeignKey(db_column='parentComId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('publication', models.ForeignKey(db_column='pubId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication')),
                ('user', models.ForeignKey(db_column='usrId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COMMENT',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(db_column='reacId', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('WARNING', 'Warning')], db_column='reacType', max_length=45)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='reacCreatedAt')),
                ('comment', models.ForeignKey(db_column='comId', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment')),
                ('user', models.ForeignKey(db_column='usrId', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'REACTION',
            },
        ),
    ]
